# 要使用MITIE管道，您将必须训练来自语料库的单词向量
language: "zh"

pipeline:
- name: "MitieNLP"
    model: "data/total_word_feature_extractor_smt.dat"
- name: "JiebaTokenizer"
    dictionary_path: "data/dict"
- name: "MitieTokenizer"
- name: "MitieEntityExtractor"
- name: "EntitySynonymMapper"
- name: "RegexFeaturizer"
- name: "MitieFeaturizer"
- name: "SklearnIntentClassifier"
- name: ResponseSelector
  epochs: 100

policies:
  - name: TEDPolicy
    epochs: 500
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy